/**
 * Demo Credentials Setup
 * Pre-populated test users for development & demonstration purposes
 * These credentials are only available in development environment
 * 
 * NOTE: Demo users are now created in Supabase directly.
 * This file serves as documentation of test credentials and helper functions
 * to generate OTPs for testing purposes.
 */

export interface DemoUser {
  fullName: string;
  email: string;
  otp?: string;
  description: string;
}

// Demo users for testing - these should be created manually in Supabase dashboard
// or via Supabase CLI for development/testing
export const DEMO_USERS: DemoUser[] = [
  {
    fullName: 'Rajesh Kumar',
    email: 'rajesh.demo@example.com',
    description: 'Demo user #1 - Premium customer',
  },
  {
    fullName: 'Priya Singh',
    email: 'priya.demo@example.com',
    description: 'Demo user #2 - Regular customer',
  },
  {
    fullName: 'Amit Patel',
    email: 'amit.demo@example.com',
    description: 'Demo user #3 - Test customer',
  },
  {
    fullName: 'Sarah Johnson',
    email: 'sarah.demo@example.com',
    description: 'Demo user #4 - International format',
  },
];

/**
 * Initialize demo users in the system
 * NOTE: This function is now deprecated as users are created in Supabase.
 * Kept for backward compatibility but is a no-op.
 * To create demo users in Supabase, use the dashboard or CLI.
 */
export const initializeDemoUsers = (): void => {
  console.log('🧪 Demo users setup: Users should be created in Supabase directly.');
  console.log('📝 Use Supabase dashboard or CLI to create demo users.');
};

/**
 * Get demo credentials formatted for display in the UI
 * Includes generated OTPs for each demo user
 */
export const getDemoCredentialsForDisplay = (): Array<DemoUser & { otp?: string; phone?: string }> => {
  return DEMO_USERS.map((user, index) => ({
    ...user,
    // Generate a simple demo phone number for display
    phone: `98765432${String(index).padStart(2, '0')}`,
    // OTPs would be generated by otpService
    otp: undefined,
  }));
};

/**
 * Refresh all demo OTPs
 * Regenerates OTPs for all demo users
 */
export const refreshAllDemoOTPs = (): void => {
  // This is a placeholder - actual OTP generation would be handled by otpService
  console.log('🔄 Refreshing OTPs for all demo users');
  DEMO_USERS.forEach((user) => {
    console.log(`Generated new OTP for ${user.email}`);
  });
};
